# Generated by Django 4.2.3 on 2023-07-19 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='string1',
            new_name='Course_Code',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='string2',
            new_name='Course_Teacher',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='string3',
            new_name='Course_Title',
        ),
    ]
